import {createAction, props} from '@ngrx/store';
import { Course } from 'src/app/services/course.model';

export const requestAllCourses = createAction('[Courses] Request All');
export const requestAllCoursesSuccess = createAction('[Courses] Request All Success', props<{courses : Course[]}>());
export const requestAllCoursesFail = createAction('[Courses] Reqeust All Fail', props<{errorMessage: string}>());
export const requestSingleCourse = createAction('[Course] Request Single', props<{courseId: string}>());
export const requestSingleCourseSuccess = createAction('[Course] Request Single Success', props<{course: Course}>());
export const requestSingleCourseFail = createAction('[Course] Request Single Fail', props<{errorMessage: string}>());
export const requestFilteredCourses = createAction('[Courses] Request Filtered', props<{title: string}>());
export const requestFilteredCoursesSuccess = createAction('[Courses] Request Filtered Success', props<{courses: Course[]}>());
export const requestFilteredCoursesFail = createAction('[Courses] Request Filtered Fail', props<{errorMessage: string}>());
export const requestDeleteCourse = createAction('[Course] Request Delete', props<{course: Course}>());
export const requestDeleteCourseFail = createAction('[Course] Request Delete Fail', props<{errorMessage: string}>());
export const requestEditCourse = createAction('[Course] Request Edit', props<{course: Course}>());
export const requestEditCoruseSuccess = createAction('[Course] Requset Edit Success', props<{course: Course}>());
export const requestEditCourseFail = createAction('[Course] Request Edit Fail', props<{errorMessage: string}>());
export const requestCreateCourse = createAction('[Course] Request Create', props<{course: Course}>());
export const requestCreateCourseSuccess = createAction('[Course] Request Create Success', props<{course: Course}>());
export const requestCreateCourseFail = createAction('[Course] Request Create Fail', props<{errorMessage: string}>());